apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ollama_ui.fullname" . }}
  labels:
    {{- include "ollama_ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ollama_ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ollama_ui.labels" . | nindent 8 }}
 {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ollama.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ollama_ui.image.repository }}:{{ .Values.ollama_ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ollama_ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ollama_ui.service.port }}
              protocol: TCP
          env:
          - name: OLLAMA_BASE_URLS
            value: http://ollama:11434
          - name: ENV
            value: dev
          - name: WEBUI_AUTH
          - name: WEBUI_NAME
            value: GenAI
          - name: WEBUI_URL
            value: http://ollama-ui.local
          - name: WEBUI_SECRET_KEY
            value: t0p-s3cr3t
          resources:
            {{- toYaml .Values.ollama_ui.resources | nindent 12 }}
          volumeMounts:
            - name: ollama-data
              mountPath: /app/backend/data
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
      volumes:
        - name: ollama-data
        {{- if .Values.persistentVolume.enabled }}
          {{- if .Values.persistentVolume.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.existingClaim }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ template "ollama_ui.fullname" . }}
          {{- end }}
        {{- end }}
        {{- with .Values.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- with .Values.tolerations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}